require "VLS_Config"
require "TimedActions/ISWashYourself"
require "TimedActions/ISWashClothing"
require "TimedActions/ISTakeWaterAction"
require "TimedActions/ISCleanBandage"

-- Vehicle tanks are not native IsoObject water fixtures. VLS keeps the actual
-- tank authoritative while the client menu is generated by the vanilla B42
-- water-source menu. The bridge actions below retain the native timed-action
-- bodies/animations and resolve the real installed vehicle tank independently
-- on client and server.
VLS.TankWash = VLS.TankWash or {}
local W = VLS.TankWash

local function integer(value)
    return type(value)=="number" and value==value and math.abs(value)<math.huge
        and value==math.floor(value)
end

function W.resolve(character,vehicleId,partId,tankId,requirePosition)
    if not VLS.isWaterTankShortcutEnabled() or not character or character:isDead() or character:getVehicle()
            or not integer(vehicleId) or not integer(tankId)
            or type(partId)~="string" or partId=="" then return nil end
    local vehicle=getVehicleById(vehicleId)
    if not vehicle or vehicle:isRemovedFromWorld() or not vehicle:isStopped()
            or not VLS.isSupportedVehicle(vehicle) then return nil end
    local tank,part=VLS.getInstalledWaterTank(vehicle,partId)
    if not tank or not part or part:getId()~=partId or tank:getID()~=tankId then return nil end
    if requirePosition and not VLS.isPlayerAtWaterTankInlet(vehicle,part,character) then return nil end
    local fluid=tank:getFluidContainer()
    if not fluid or not VLS.isPureWaterFluid(fluid) or not fluid:canPlayerEmpty() then return nil end
    return vehicle,part,tank,fluid
end

function W.clothingAmounts(item)
    local blood,dirt=0,0
    if instanceof(item,"Clothing") or instanceof(item,"InventoryContainer") then
        local covered=BloodClothingType.getCoveredParts(item:getBloodClothingType())
        if covered then
            for i=0,covered:size()-1 do blood=blood+item:getBlood(covered:get(i)) end
        end
        dirt=math.max(0,item:getDirtiness())
    else
        blood=math.max(0,item:getBloodLevel())
    end
    return blood,dirt
end

function W.isWashable(item)
    if not item then return false end
    local blood,dirt=W.clothingAmounts(item)
    return blood+dirt>0 or item:getItemAfterCleaning()~=nil
end

local function refreshClothing(action)
    local inventory=action.character and action.character:getInventory()
    local item=action.item and inventory and inventory:getItemWithIDRecursiv(action.item:getID())
    if not item or not W.isWashable(item) then return false end
    action.item=item
    action.bloodAmount,action.dirtAmount=W.clothingAmounts(item)
    action.soaps=inventory:getSoapList(nil,true)
    action.noSoap=ISWashClothing.GetSoapRemaining(action.soaps)<=0
    return true
end

local function resolveAction(action)
    return W.resolve(action.character,action.vehicleId,action.partId,action.tankId,true)
end

local function syncTank(vehicle,part,tank)
    VLS.syncVehicleWaterTank(vehicle,part)
    tank:syncItemFields()
    vehicle:transmitPartModData(part)
    vehicle:transmitPartItem(part)
end

-- Native wash completion consumes this bounded sink after the real tank has
-- already been debited server-side. This preserves vanilla cleaning/soap rules
-- without ever creating free water.
local function sinkFor(action,budget)
    local sink={used=0}
    function sink:getFluidAmount()
        if budget then return budget end
        local _,_,_,fluid=W.resolve(action.character,action.vehicleId,action.partId,action.tankId,false)
        return fluid and math.max(0,math.floor(fluid:getAmount())) or 0
    end
    function sink:useFluid(amount)
        assert(budget and amount>=0 and self.used+amount<=budget+0.0001,"VLS wash budget exceeded")
        self.used=self.used+amount
        return amount
    end
    function sink:transmitModData() end
    return sink
end

-- Only the pre-effect reservation is reversible. Once vanilla has touched
-- soap, clothing or the character, seal the action even on an exception: a
-- refund/retry could otherwise create free cleaning or duplicate bandages.
local function reserveWater(fluid,amount)
    local snapshot=FluidContainer.CreateContainer()
    snapshot:setCapacity(fluid:getCapacity())
    snapshot:copyFluidsFrom(fluid)
    local before=fluid:getAmount()
    local ok=pcall(function()
        fluid:removeFluid(amount)
        assert(math.abs(before-fluid:getAmount()-amount)<=0.0001,"water debit mismatch")
    end)
    if not ok then fluid:copyFluidsFrom(snapshot) end
    FluidContainer.DisposeContainer(snapshot)
    return ok
end

local function completeWash(action,nativeComplete,body)
    if isClient() or action.vlsCommitted then return false end
    local vehicle,part,tank,fluid=resolveAction(action)
    if not vehicle then return false end
    if not body and (not refreshClothing(action)
            or action.item:getContainer()~=action.character:getInventory()) then return false end
    local required=body and math.min(ISWashYourself.GetRequiredWater(action.character),
        math.floor(fluid:getAmount())) or ISWashClothing.GetRequiredWater(action.item)
    if required<=0 or required>fluid:getAmount() then return false end
    if not reserveWater(fluid,required) then
        syncTank(vehicle,part,tank)
        print("[VLS 3.8.8] wash rejected: native water debit mismatch")
        return false
    end
    action.vlsCommitted=true
    if body then action.soaps=action.character:getInventory():getSoapList(nil,false) end
    local oldSink=action.sink
    action.sink=sinkFor(action,required)
    local ok,result=pcall(nativeComplete,action)
    action.sink=oldSink
    syncTank(vehicle,part,tank)
    if not ok then
        print("[VLS 3.8.8] native wash failed after water debit: "..tostring(result))
        return false
    end
    return result==true
end

VLSWashYourselfFromTank=ISWashYourself:derive("VLSWashYourselfFromTank")
function VLSWashYourselfFromTank:isValid()
    local vehicle,_,_,fluid=resolveAction(self)
    return not self.vlsCommitted and vehicle~=nil and fluid:getAmount()>=1
        and ISWashYourself.GetRequiredWater(self.character)>0
end
function VLSWashYourselfFromTank:update()
    local vehicle=resolveAction(self)
    if vehicle then self.character:faceThisObject(vehicle) end
    self.character:setMetabolicTarget(Metabolics.LightDomestic)
end
function VLSWashYourselfFromTank:getDuration()
    self.soaps=self.character:getInventory():getSoapList(nil,false)
    self.sink=sinkFor(self)
    return ISWashYourself.getDuration(self)
end
function VLSWashYourselfFromTank:complete()
    return completeWash(self,ISWashYourself.complete,true)
end
function VLSWashYourselfFromTank:new(character,vehicleId,partId,tankId)
    local o=ISBaseTimedAction.new(self,character)
    o.vehicleId=vehicleId;o.partId=partId;o.tankId=tankId
    o.forceProgressBar=true
    o.maxTime=o:getDuration()
    return o
end

VLSWashClothingFromTank=ISWashClothing:derive("VLSWashClothingFromTank")
function VLSWashClothingFromTank:isValid()
    local vehicle,_,_,fluid=resolveAction(self)
    if self.vlsCommitted or not vehicle or not refreshClothing(self) then return false end
    if not isClient() and self.item:getContainer()~=self.character:getInventory() then return false end
    return fluid:getAmount()>=ISWashClothing.GetRequiredWater(self.item)
end
function VLSWashClothingFromTank:update()
    local vehicle=resolveAction(self)
    if vehicle then self.character:faceThisObject(vehicle) end
    self.item:setJobDelta(self:getJobDelta())
    self.character:setMetabolicTarget(Metabolics.HeavyDomestic)
end
function VLSWashClothingFromTank:getDuration()
    if not refreshClothing(self) then return 0 end
    return ISWashClothing.getDuration(self)
end
function VLSWashClothingFromTank:complete()
    return completeWash(self,ISWashClothing.complete,false)
end
function VLSWashClothingFromTank:new(character,vehicleId,partId,tankId,item)
    local o=ISBaseTimedAction.new(self,character)
    o.vehicleId=vehicleId;o.partId=partId;o.tankId=tankId;o.item=item
    o.sink=sinkFor(o)
    o.forceProgressBar=true
    o.maxTime=o:getDuration()
    return o
end

-- Vanilla take/drink action with only the fluid endpoint replaced. The vehicle
-- is a real world object for facing/animation; the installed item remains the
-- authoritative source of fluid.
VLSTakeWaterFromTank=ISTakeWaterAction:derive("VLSTakeWaterFromTank")
function VLSTakeWaterFromTank:isValid()
    local vehicle,_,_,fluid=resolveAction(self)
    if not vehicle or fluid:getAmount()<=0 or not self.waterUnit or self.waterUnit<=0 then return false end
    if self.item then
        local inventory=self.character:getInventory()
        local item=inventory and inventory:getItemWithIDRecursiv(self.item:getID())
        if item~=self.item or not item:getFluidContainer() then return false end
        if not FluidContainer.CanTransfer(fluid,item:getFluidContainer()) then return false end
    end
    return not self.character:hasFullInventory()
end
function VLSTakeWaterFromTank:waitToStart()
    local vehicle=resolveAction(self)
    if vehicle then self.character:faceThisObject(vehicle) end
    return self.character:shouldBeTurning()
end
VLSTakeWaterFromTank.updateUse=ISTakeWaterAction.updateUse
function VLSTakeWaterFromTank:update()
    if self.item then self.item:setJobDelta(self:getJobDelta()) end
    local vehicle=resolveAction(self)
    if vehicle then self.character:faceThisObject(vehicle) end
    if not isClient() then
        local progress=self.netAction and self.netAction:getProgress() or self:getJobDelta()
        self:updateUse(progress)
    end
end
function VLSTakeWaterFromTank:start()
    local vehicle=resolveAction(self)
    if not vehicle then return end
    self.waterObject=vehicle

    -- B42.20 ISTakeWaterAction:start() classifies normal world water sources
    -- through waterObject:getSprite():getName(). BaseVehicle is valid for facing
    -- and our fluid endpoint, but it has no world-object sprite name, which makes
    -- vanilla luautils.stringStarts(nil, ...) throw. Keep the vanilla take/drink
    -- action setup while skipping only that world-sprite classification step.
    if self.item then
        self.item:setBeingFilled(true)
        self.item:setJobType(getText("ContextMenu_Fill") .. self.item:getName())
        self.item:setJobDelta(0.0)
        self.sound=self.character:playSound(self.item:getFillFromTapSound() or "GetWaterFromTap")
        self:setAnimVariable("PourType",self.item:getPourType())
        self:setActionAnim("fill_container_tap")
        if self.character:isSecondaryHandItem(nil) then
            self:setOverrideHandModels(nil,self.item:getStaticModel())
        else
            self:setOverrideHandModels(self.item:getStaticModel(),nil)
        end
    else
        self.sound=self.character:playSound("DrinkingFromTap")
        self:setActionAnim("drink_tap")
        self:setOverrideHandModels(nil,nil)
    end
    self.character:reportEvent("EventTakeWater")
end
function VLSTakeWaterFromTank:transferFluid(amount)
    if isClient() or not amount or amount<=0 then return end
    local vehicle,part,tank,fluid=resolveAction(self)
    if not vehicle then return end
    local moved=0
    if self.item then
        local inventory=self.character:getInventory()
        local item=inventory and inventory:getItemWithIDRecursiv(self.item:getID())
        local target=item and item:getFluidContainer()
        if not target or not FluidContainer.CanTransfer(fluid,target) then return end
        local before=fluid:getAmount()
        fluid:transferTo(target,amount)
        moved=math.max(0,before-fluid:getAmount())
        self.item=item
        item:syncItemFields()
        sendItemStats(item)
    else
        local temp=FluidContainer.CreateContainer()
        local before=fluid:getAmount()
        fluid:transferTo(temp,amount)
        moved=math.max(0,before-fluid:getAmount())
        if moved>0 then self.character:DrinkFluid(temp,1) end
        FluidContainer.DisposeContainer(temp)
    end
    if moved>0 then syncTank(vehicle,part,tank) end
end
VLSTakeWaterFromTank.stopSound=ISTakeWaterAction.stopSound
VLSTakeWaterFromTank.stop=ISTakeWaterAction.stop
VLSTakeWaterFromTank.perform=ISTakeWaterAction.perform
VLSTakeWaterFromTank.complete=ISTakeWaterAction.complete
VLSTakeWaterFromTank.serverStart=ISTakeWaterAction.serverStart
VLSTakeWaterFromTank.animEvent=ISTakeWaterAction.animEvent
VLSTakeWaterFromTank.getDuration=ISTakeWaterAction.getDuration
function VLSTakeWaterFromTank:new(character,vehicleId,partId,tankId,item)
    local o=ISBaseTimedAction.new(self,character)
    o.vehicleId=vehicleId;o.partId=partId;o.tankId=tankId;o.item=item
    local vehicle,_,_,fluid=W.resolve(character,vehicleId,partId,tankId,true)
    if not vehicle then o.maxTime=1;o.waterUnit=0;return o end
    o.waterObject=vehicle
    o.waterTaintedCL=fluid:contains(Fluid.TaintedWater)
    local available=fluid:getAmount()
    if item and item:getFluidContainer() then
        o.startUsedAmount=item:getFluidContainer():getAmount()
        o.endUsedAmount=item:getFluidContainer():getCapacity()
        local freeInventoryCapacity=character:getFreeInventoryCapacity()
        if item:isEquipped() or character:isEquippedClothing(item) then
            freeInventoryCapacity=freeInventoryCapacity/ZomboidGlobals.EquippedOrWornEncumbranceMultiplier
        end
        o.waterUnit=math.max(0,math.min(o.endUsedAmount-o.startUsedAmount,available,freeInventoryCapacity))
    else
        local thirst=character:getStats():get(CharacterStat.THIRST)*2
        o.waterUnit=math.max(0,math.min(thirst,available))
        o.startUsedAmount=0
        o.startThirst=thirst
        o.endUsedAmount=math.min(o.waterUnit,1)
    end
    o.maxTime=o:getDuration()
    return o
end

-- Dirty-bandage cleaning is also generated by the vanilla water-source menu.
-- Keep the native recipe/result semantics while using the real vehicle tank.
VLSCleanBandageFromTank=ISCleanBandage:derive("VLSCleanBandageFromTank")
function VLSCleanBandageFromTank:isValid()
    local vehicle,_,_,fluid=resolveAction(self)
    return vehicle~=nil and fluid:getAmount()>=1
        and self.item and self.item:getContainer()==self.character:getInventory()
end
function VLSCleanBandageFromTank:waitToStart()
    local vehicle=resolveAction(self)
    if vehicle then self.character:faceThisObject(vehicle) end
    return self.character:shouldBeTurning()
end
function VLSCleanBandageFromTank:update()
    self.item:setJobDelta(self:getJobDelta())
    local vehicle=resolveAction(self)
    if vehicle then self.character:faceThisObject(vehicle) end
end
VLSCleanBandageFromTank.start=ISCleanBandage.start
VLSCleanBandageFromTank.stopSound=ISCleanBandage.stopSound
VLSCleanBandageFromTank.stop=ISCleanBandage.stop
VLSCleanBandageFromTank.perform=ISCleanBandage.perform
VLSCleanBandageFromTank.getDuration=ISCleanBandage.getDuration
function VLSCleanBandageFromTank:complete()
    if isClient() or self.vlsCommitted then return false end
    local vehicle,part,tank,fluid=resolveAction(self)
    if not vehicle or fluid:getAmount()<1 or self.item:getContainer()~=self.character:getInventory() then return false end
    if not reserveWater(fluid,1) then
        syncTank(vehicle,part,tank)
        return false
    end
    self.vlsCommitted=true
    local original=self.waterObject
    self.waterObject=sinkFor(self,1)
    local ok,result=pcall(ISCleanBandage.complete,self)
    self.waterObject=original
    syncTank(vehicle,part,tank)
    if not ok then
        print("[VLS] native bandage completion failed after reserved water: "..tostring(result))
        return false
    end
    return result==true
end
function VLSCleanBandageFromTank:new(character,vehicleId,partId,tankId,item,recipe)
    local o=ISBaseTimedAction.new(self,character)
    o.vehicleId=vehicleId;o.partId=partId;o.tankId=tankId
    o.item=item;o.result=recipe:getResult():getType();o.recipe=recipe
    o.maxTime=o:getDuration()
    return o
end

return W
